"""Initial migration

Revision ID: 61947be3191b
Revises: 
Create Date: 2024-09-09 17:18:12.539699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61947be3191b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dress_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dress_model')
    # ### end Alembic commands ###
