"""cart added

Revision ID: 8b1b855e395b
Revises: 9998e4c263c6
Create Date: 2024-09-10 16:20:47.778227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b1b855e395b'
down_revision = '9998e4c263c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('add_cart',
    sa.Column('cart_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cart', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart'], ['dress.id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.drop_table('dress_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dress_model',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image', mysql.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('add_cart')
    op.drop_table('dress')
    # ### end Alembic commands ###
