"""Image field added

Revision ID: 9998e4c263c6
Revises: 61947be3191b
Create Date: 2024-09-10 09:20:17.727663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9998e4c263c6'
down_revision = '61947be3191b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dress_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dress_model', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
