"""added

Revision ID: 9bb3c56ffaec
Revises: 8b1b855e395b
Create Date: 2024-09-21 14:59:41.143032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb3c56ffaec'
down_revision = '8b1b855e395b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_table',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('message', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_table')
    # ### end Alembic commands ###
